# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from echo_server import echo_pb2 as echo__server_dot_echo__pb2


class EchoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Echo = channel.unary_unary(
                '/EchoService/Echo',
                request_serializer=echo__server_dot_echo__pb2.TextMessage.SerializeToString,
                response_deserializer=echo__server_dot_echo__pb2.TextMessage.FromString,
                )
        self.EchoMany = channel.stream_stream(
                '/EchoService/EchoMany',
                request_serializer=echo__server_dot_echo__pb2.TextMessage.SerializeToString,
                response_deserializer=echo__server_dot_echo__pb2.TextMessage.FromString,
                )


class EchoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Echo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EchoMany(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EchoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Echo': grpc.unary_unary_rpc_method_handler(
                    servicer.Echo,
                    request_deserializer=echo__server_dot_echo__pb2.TextMessage.FromString,
                    response_serializer=echo__server_dot_echo__pb2.TextMessage.SerializeToString,
            ),
            'EchoMany': grpc.stream_stream_rpc_method_handler(
                    servicer.EchoMany,
                    request_deserializer=echo__server_dot_echo__pb2.TextMessage.FromString,
                    response_serializer=echo__server_dot_echo__pb2.TextMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'EchoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EchoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Echo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/EchoService/Echo',
            echo__server_dot_echo__pb2.TextMessage.SerializeToString,
            echo__server_dot_echo__pb2.TextMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EchoMany(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/EchoService/EchoMany',
            echo__server_dot_echo__pb2.TextMessage.SerializeToString,
            echo__server_dot_echo__pb2.TextMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
